version: '3.0'

services:
  csapp_running_env:
    build:
      context: ./docker
      args:
        SSH_USER: ${SSH_USER}
        SSH_PASS: ${SSH_PASS}
    hostname: csapp_running_env
    # stdin_open: true
    # tty: true
    volumes:
      - ./labs:/home/${SSH_USER}/labs
      - ./test:/home/${SSH_USER}/test
    ports:
      - "2222:22"